version: "3.9"

services:

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - database
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: orion
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: database

  python:
    image: python:3.8-alpine  # Alterada para a imagem Python Alpine
    restart: always
    volumes:
      - ./flows:/app
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - database
    command: >
      sh -c "apk add --no-cache build-base libffi-dev openssl-dev && pip install -r /app/requirements.txt && python /app/run.py"  # Instala dependências e executa run.py
    tty: true

volumes:
  postgres:
